baseURL: "https://tangyanhan.github.io/"
languageCode: "zh-cn"
title: "Ethan Tang"
theme: hyde
math: true

menus:
  main:
  - name: Github
    url: 'https://github.com/tangyanhan/'
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/ethan-tang-6063177a/'
params:
  description: 'Ethan Tang technical share'
  copyright: Yanhan Tang
  themeColor: "theme-base-0b"
  beian: 苏ICP备19057256号-1
  math: true

  enableSidebarTags: true

  # footer
  showPoweredBy: true
  showFeedLinks: true
  enableThemeChange: false
  themeOptions: ["light"]

markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 1
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: perldoc
    tabWidth: 4